version: 2

project_name: swenv

builds:
  - id: swenv
    main: .
    binary: swenv
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

homebrew_casks:
  - name: swenv
    repository:
      owner: BasileosFelices
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Casks
    homepage: https://github.com/BasileosFelices/swenv
    description: "Quickly switch between different .env environment files"
    license: MIT
    binaries:
      - swenv
    commit_msg_template: "chore: update {{ .ProjectName }} to v{{ .Tag }}"
